version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: granja_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: granja
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: granja_app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    stdin_open: true
    tty: true

volumes:
  mysql_data:
